### ISSUE TITLE
SELF_URL_PATH - startup failed

### ISSUE THREAD

**Issue by rocknjoekudo** [serl/ttrss-heroku#11]
Hi,

First of all, it is really a long time since last time I created a ticket and communicate with you. Your contributions to open-source communities are really appreciate! Well done like always.
During the last two weeks, I am struggling with the following error after I triggered rebuilding to my Heroku instance.

> Startup failed
> 
> Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:
> Please set Config::get(Config::SELF_URL_PATH) to the correct value detected for your server: [sensitive content erased] (you're using: )

I tried to fix this issue by myself. I modified **ttrss-config.php** with a static url of my instance, but it failed. I also tried to **heroku config:set** to override the value, but it also failed. Could you please leave any suggestion on this issue? Thanks in advance.

**Comment by DylanXie123** [comment]
Same problem here

**Comment by serl** [comment]
Hello,
I see, actually the config file format changed on tt-rss side, so I've to update it here.

**Comment by serl** [comment]
Should be solved now.
Thanks for the heads up :)

WARNING! If you installed plugins via the ~~TTRSS_PLUGINS~~ env variable, you should change its name. More details in the note here https://github.com/serl/ttrss-heroku#adding-plugins

**Comment by rocknjoekudo** [comment]
> Should be solved now.
> Thanks for the heads up :)
> 
> WARNING! If you installed plugins via the ~TTRSS_PLUGINS~ env variable, you should change its name. More details in the note here https://github.com/serl/ttrss-heroku#adding-plugins

Thank you very much, serl! I can confirm that it just works like charm!
