### ISSUE TITLE
Deployment Error: Base database schema missing

### ISSUE THREAD

**Issue by nirmalhk7** [serl/ttrss-heroku#13]
Not sure if this is something with ttrss or this Heroku extension of it, but please help.

I've followed the README.md but I get this error when I open the app:

> Base database schema is missing. Either load it manually or perform a migration (update.php --update-schema)

**Comment by serl** [comment]
Hello, maybe #14 fixes this, could you try again from the branch update-schema? (`git fetch && git push heroku origin/update-schema:master`)

Thanks!

**Comment by keheliya** [comment]
That command didn't fix the issue. 

Then, I logged into the heroku bash console and executed the following commands.
```
./ttrss-init.sh
php tt-rss/update.php --update-schema=force-yes
```
This fixed it. (Had to execute the first command also because I noticed there was no tt-rss directory.)

**Comment by nirmalhk7** [comment]
Apologies I lost track of this issue, but I was able to solve this by re-running it. 

I shall close it therefore. Thank you

**Comment by LindenXing** [comment]
I also get this error,

> That command didn't fix the issue.
> 
> Then, I logged into the heroku bash console and executed the following commands.
> 
> ```
> ./ttrss-init.sh
> php tt-rss/update.php --update-schema=force-yes
> ```
> 
> This fixed it. (Had to execute the first command also because I noticed there was no tt-rss directory.)

it does't work.

**Comment by LindenXing** [comment]
> That command didn't fix the issue.
> 
> Then, I logged into the heroku bash console and executed the following commands.
> 
> ```
> ./ttrss-init.sh
> php tt-rss/update.php --update-schema=force-yes
> ```
> 
> This fixed it. (Had to execute the first command also because I noticed there was no tt-rss directory.)

I also get the error,but it doesn't work

**Comment by LindenXing** [comment]
> Apologies I lost track of this issue, but I was able to solve this by re-running it.
> 
> I shall close it therefore. Thank you

how do you fix it, just re-running it?I try several times, but it still have the error.
