### ISSUE TITLE
Error while pushing this repository to Heroku

### ISSUE THREAD

**Issue by rocknjoekudo** [serl/ttrss-heroku#2]
First, thank you for creating this PaaS version of TTRSS for us. Personally I believe this is a great idea.

Issue:
I followed README to deploy my own Heroku app. However, I was not able to successfully execute "git push heroku master" command. The error message is following:

> rj@rj:~/src/ttrss-heroku$ git push heroku master
Counting objects: 62, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (60/60), done.
Writing objects: 100% (62/62), 26.77 KiB | 2.97 MiB/s, done.
Total 62 (delta 24), reused 0 (delta 0)
remote: Git submodules detected, installing:
remote: Submodule 'tt-rss' (https://git.tt-rss.org/fox/tt-rss) registered for path 'tt-rss'
remote: Cloning into 'tt-rss'...
remote: fatal: unable to access 'https://git.tt-rss.org/fox/tt-rss/': gnutls_handshake() failed: Handshake failed
remote: Clone of 'https://git.tt-rss.org/fox/tt-rss' into submodule path 'tt-rss' failed
remote: 
remote: !	Push rejected, submodule install failed
remote: 
To https://git.heroku.com/**********.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/**********.git

A naive guess: I think the Git server of TTRSS simply blocked Git push connection from Heroku. I tried to modify .gitmodules file to use SSH instead of HTTPS, but this failed, too. A robust solution is to create a TTRSS Git repository on GitHub, and modify .gitmodules file. 

Could you please leave me any suggestion to fix this issue? I am sorry for not being an expert of deploying an app to a PaaS platform, or a native English speaker. Thank you for your work and patience.

**Comment by rocknjoekudo** [comment]
Update: I successfully deployed my own TTRSS instance on Heroku, by modifying the repository address of TT-RSS. Obviously There is obviously an issue of Heroku cloning code from the official repository. Personally I have no idea how to solve this issue. Anyway, there is still a temporary solution.

**Comment by serl** [comment]
Hello,

I'm not an expert as well (I mean, it simply worked when I did it...), but I would say it could be either a HTTPS certificate error, or some domain white/blacklisting on the Heroku side.

Now I cannot look into it in detail, as I'm out for some days. I clearly would like to find a way in which TTRSS sources come from the official source.

Anyway, thanks for the heads up!

**Comment by serl** [comment]
Sorry for the delay.
I actually found a solution directly from the [official website](https://tt-rss.org/) (thanks Andrew!):

> if you can't check out from main git repository (one common reason is Cloudflare disliking your IP), try using Gitlab mirror [here](https://gitlab.com/gothfox/tt-rss).

I also updated code and dependencies, everything seems to be working again!

**Comment by rocknjoekudo** [comment]
> 
> 
> Sorry for the delay.
> I actually found a solution directly from the [official website](https://tt-rss.org/) (thanks Andrew!):
> 
> > if you can't check out from main git repository (one common reason is Cloudflare disliking your IP), try using Gitlab mirror [here](https://gitlab.com/gothfox/tt-rss).
> 
> I also updated code and dependencies, everything seems to be working again!

Thank you very much for your update! Your project really means something to me!
