### ISSUE TITLE
Not an Issue. Fever API Plugin

### ISSUE THREAD

**Issue by alexraskin** [serl/ttrss-heroku#3]
Hello, do you think it would be possible to add the fever api plugin to this deploy? 

https://github.com/DigitalDJ/tinytinyrss-fever-plugin 

Thank you

**Comment by serl** [comment]
Hello, I guess so...
Try to add the installation commands to `post-install.sh`.
Let me know if it works, I would add some helper to generalize this ;)

**Comment by serl** [comment]
Sorry for the long wait. Now you can add custom plugins! More info in the appropriate section of the readme.
