### ISSUE TITLE
A missing PHP module "intl" after updating to 19.8. A naive fix included as well.

### ISSUE THREAD

**Issue by rocknjoekudo** [serl/ttrss-heroku#5]
Again, thank Sergio Livi for this AMAZING Heroku project for TT-RSS! I am NOT a native English speaker, so this post may lead a confusion to you guys. A thousand apologies.

Recently, TT-RSS released a stable version 19.8. It requires a new essential PHP module called "intl", otherwise there is a fatal error which refuses starting TT-RSS. I had zero knowledge about PHP before solving this issue. So the quick fix below is very naive to professionals.

Step 1: add missing PHP extension `ext-intl` to composer.json.
Step 2: use `composer update --lock` command to generate a new composer.lock. This requires installations of `PHP 7.3`, PHP extensions including `mbstring`, `gd`, `intl`, and `simplexml` locally. Different OS may have different methods of such installations.
Step 3: commit all changes locally, and push the updated versions to Heroku.

Successfully tested for my own Heroku projects. For others who want a quicker solution, I uploaded the updated `composer.json` and `composer.lock` in the OneDrive link below.

[https://1drv.ms/u/s!Ajdq4RAFv61dddhbMUFGXod_XZ8?e=4LkGOj](https://1drv.ms/u/s!Ajdq4RAFv61dddhbMUFGXod_XZ8?e=4LkGOj)

**Comment by serl** [comment]
Added! Thanks!
